### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/message#14]
We should be able to format Requests/Responses to string.

## Basic interface

``` php
<?php

namespace Http\Message;

use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

/**
 * Formats a request or a response into string.
 *
 * @author Márk Sági-Kazár <mark.sagikazar@gmail.com>
 */
interface Formatter
{
    /**
     * Formats a request.
     *
     * @param RequestInterface $request
     *
     * @return string
     */
    public function formatRequest(RequestInterface $request);

    /**
     * Formats a response.
     *
     * @param ResponseInterface $response
     *
     * @return string
     */
    public function formatResponse(ResponseInterface $response);
}
```

## Some questions

- Should we separate Request/Response format method into separate interfaces? (Like in case of message factories)

## Default implementations

- Simple text formatter: https://github.com/php-http/plugins/blob/master/src/Normalizer/Normalizer.php
- Curl command formatter: https://github.com/namshi/cuzzle

**Comment by dbu** [comment]
+1
not sure about separating. a guzzle formatter makes absolutely no sense for a response. but it could just reuse the simple text formatter for the response and do its cool stuff on requests. that way, things are much simpler than having two interfaces that 90% of the time are provided by the same formatter.
