### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/message#15]
Move and finalize php-http/cookie here.

**Comment by joelwurtz** [comment]
What need to be finalized in  php-http/cookie ?

**Comment by sagikazarmark** [comment]
https://github.com/php-http/cookie/issues
https://github.com/php-http/cookie/pulls

I am also thinking about making the cookie jar itself immutable. Didn't have the time to do it though.

Feel free to play with it.

**Comment by joelwurtz** [comment]
CookieJar don't need to be immutable as it's not IMO a data object but rather a service which should only transfer / create cookie from a specific storage.
