### ISSUE TITLE
Automatically register stream filters

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/message#16]
Currently filters are registered upon access to a Chunk/Dechunk stream:

https://github.com/php-http/message/blob/master/src/Encoding/ChunkStream.php#L17

As I can see some of the filters (chunk, dechunk) are implemented in the package for BC reasons (for example HHVM does not have chunk/dechunk filters).

Should we register these classes as stream filters automatically (eg. using composer autoloading)?

**Comment by joelwurtz** [comment]
Would probably be better, but don't know if it's actually possible ?

**Comment by sagikazarmark** [comment]
I meant something like this: https://getcomposer.org/doc/04-schema.md#files

**Comment by joelwurtz** [comment]
:+1: then
