### ISSUE TITLE
Base URL message factory

### ISSUE THREAD

**Issue by jakzal** [php-http/message#39]
Having to prefix all the calls with a base URL is annoying:

```
$factory->createRequest('GET', 'http://example.com/foo');
```

It could be avoided if we implemented something like the following that would include the base url for us:

```php
$factory = new BaseUrlMessageFactory('http://example.com', new GuzzleMessageFactory());
$request = $factory->createRequest('GET', '/foo');
```

The advantage is that we wouldn't need to deal with base url in the place where the factory is used.

What do you think?

**Comment by xabbuh** [comment]
It looks like the [AddHostPlugin](https://github.com/php-http/plugins/blob/master/src/AddHostPlugin.php) does this job (it doesn't seem to have documentation right yet).

**Comment by jakzal** [comment]
Moreless ;) cheers!

**Comment by sagikazarmark** [comment]
Be aware of the way how PSR-7 describes URI trailing slashes a bit illogical IMO. See https://github.com/php-http/plugins/pull/42#issuecomment-171611857

**Comment by jakzal** [comment]
Actually, i'd love to be able to pass a string there :/
