### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/message#4]
I started to work on the message package and already moved some stuff to it.

I found an inconsistency issue:

We have message factory interfaces in the message-factory package. This is a contract package, and I think it would be better to have it that way. The namespace is Http\Message.

The message factory implementations are moved here from the utils package. The namespace is Http\Message as well, so factories are in Http\Message\*Factory namespaces. Eg. Http\Message\MessageFactory\GuzzleMessageFactory.

We also have decorators. Originally they were in the Http\Message namespace as well, but I moved them in this package one level down to Http\Message\Decorator.

So we have an inconsistency here: Http\Message\MessageFactory, but Http\Message\Decorator\RequestDecorator.

The extra thing is that the message factory package is already tagged as 1.0, which does not allow us to change it's namespace without major version change.

So, should we just leave the situation as is, or should we move Decorators back to the Http\Message namespace for consistency?

**Comment by dbu** [comment]
i don't feel this naming is very bad. its all about Http\Message and we have the two sub-packages MessageFactory and Decorator. seems fine to me.

**Comment by sagikazarmark** [comment]
Actually it is more than two: MessageFactory, StreamFactory and UriFactory.

**Comment by dbu** [comment]
right. but that still feels ok to me.

**Comment by sagikazarmark** [comment]
Ok, thanks for the feedback.
