### ISSUE TITLE
Response builder broke header value

### ISSUE THREAD

**Issue by snapshotpl** [php-http/message#41]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.2.0

#### Actual Behavior

Curl client (and maybe more) using `Http\Message\Builder\ResponseBuilder`. When client adds `Content-Type: application/hal+json` header using `addHeader` method, created response contains `Content-Type: application/hal json`

#### Expected Behavior

Created response should contains valid header value as it's in raw response.

#### Steps to Reproduce

Send request to get response with header contains `+` eg. `Content-Type: application/hal+json`

#### Possible Solutions

Remove / fix decoding in https://github.com/php-http/message/blob/master/src/Builder/ResponseBuilder.php#L139

**Comment by sagikazarmark** [comment]
@snapshotpl sorry for not answering earlier. Just for you to know, this issue is being taken care of.
