### ISSUE TITLE
Missing v1.4.0 tag

### ISSUE THREAD

**Issue by ajgarlag** [php-http/message#62]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      |  b86b453

#### Actual Behavior

The v1.4.0 tag that corresponds to the version 1.4.0 described in the CHANGELOG does not exist.

**Comment by Nyholm** [comment]
You are correct, there was some miscommunication on Slack. It fell between chairs. I've tagged 1.4.0 now.
