### ISSUE TITLE
Implicit vs explicit dependencies

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/message#8]
Currently there are a few implicit dependencies declared:

- Guzzle PSR7 and Diactoros which are fine that way
- clue/stream-filter and ext-zlib which are required by the Encoding part of the package

Question: should the latter to be implicitly or explicitly required?

**Comment by joelwurtz** [comment]
Not sur if this library should be in the message common, but for encoding to work we need absolutely the clue/stream-filter library, ext-zlib is necessary for compression / decompression

**Comment by sagikazarmark** [comment]
Well, it works with streams, so I think there is place for it here. Whether it SHOULD be here or not is another question.

We can suggest those dependencies in order to make sure they work. Or we can require them, but I have the feeling that in most cases those dependencies won't even be used.

**Comment by dbu** [comment]
lets keep them optional. particularly ext-zlib could be a pain if the
php extension is not available.

**Comment by sagikazarmark** [comment]
I tend to agree. I guess the question is whether merging the encoding library worth the making the dependencies optional.

**Comment by dbu** [comment]
if stream-filter is needed for everything of the encoding part, i am ok to include it as long as it does not have a bunch of other dependencies.

**Comment by sagikazarmark** [comment]
I meant having the encoding thing in the message worth to make these dependencies optional. I would rather keep it optional, maybe the stream filter thing could be a requirement.

Other option is to leave the encoding package as is, but it is also strictly message stuff.

**Comment by sagikazarmark** [comment]
No dependencies.

**Comment by dbu** [comment]
then lets add the stream-filter thingy as depencency i would say.
