### ISSUE TITLE
Oauth 2 authentication plugin

### ISSUE THREAD

**Issue by mxr576** [php-http/message#97]
Is there any plan for adding an Oauth 2 authentication plugin to this library? I saw you could not convince thephpleague/oauth2-client to move away from Guzzle.

https://github.com/thephpleague/oauth2-client/pull/538

**Comment by mxr576** [comment]
I only found this plugin, but this is for Oauth 1 
https://github.com/xabbuh/oauth1-authentication

**Comment by joelwurtz** [comment]
Personally i would prefer have this as a separate library.

**Comment by Nyholm** [comment]
I think it would be great to have an oauth2 plugin. But it should be in a package named php-http/oauth2-plugin.

**Comment by mxr576** [comment]
No doubt, +1 for having this implemented in a separate library, but is there a concrete plan for this?

**Comment by joelwurtz** [comment]
Not really, if you want to do it feel free and ping us on that repo (here or in slack), don't mind having this in php-http with you as maintainer.

**Comment by dbu** [comment]
to summarize: oauth2 has too much external dependency to be part of the message package. we are open for a oauth2 plugin in the php-http organization if somebody volunteers to maintain it.
